enabled: true
exclude: []
changed_paths:
    maximum: 1000
    outcome: error
remote_files: []
auto: true
commit_template: |
    Restyled by ${restyler.name}
pull_requests: true
statuses: true
restylers:
    - "*"
